ArtisanFinder/urls.py
from django.contrib import admin
from django.urls import path

from . import views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import authenticate, login
from .forms import LoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil_view, name='home'),
    path('services/', views.services_view, name='services'),
    path('artisan/', views.trouverArtisan_view, name='artisan'),
    path('connexion/', views.login_view, name='login'),
    path('espaceArtisan/', views.espaceArtisan_view, name='espace-artisan'),
    path('contact/', views.contact_view, name='contact'),
    path('apropos/', views.apropos_view, name= 'apropos'),
    path('cgu/',views.cgu_view, name= 'cgu'),
    path('cgv/', views.cgv_view, name= 'cgv'),
    path('mentions-legales/', views.mentions_view, name= 'mentions-legales'),
    path('vieprivee/', views.vieprivee_view, name= 'vieprivee'),
    path('equipe/', views.equipe_view, name = 'equipe'),
    path('inscription/',views.inscription_view, name='inscription'),
    path('register/', views.profile_view, name='register'),
    path('password-oublie/', views.passwor_oublie_view, name='password-oublie'),
    path('choix/', views.choix_view, name= 'choix-inscription'),
    path('clientRegistration/', views.inscription_client_view, name= 'client-inscription'),
    path('profil/<int:artisan_id>/', views.profile_view, name='profil'),
    path('artisan/<int:artisan_id>/edit/', views.edit_profile_view, name='edit_profile_view'),
    path('artisan/change-password/', views.change_password_view, name='change_password_view'),
    path('artisan/<int:artisan_id>/add-portfolio-photo/', views.add_portfolio_photo_view, name='add_portfolio_photo_view'),
    # path('profil/', views.profil_view, name='profil'),
    
     
    
     ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

   

ArtisanFinder/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser




# Model de modification de profil Artisan :
class Artisan(AbstractUser):
    nom = models.CharField(max_length=50, blank=False)
    prenom = models.CharField(max_length=70, blank=False)
    genre = models.CharField(max_length=10, choices=[('Homme', 'Homme'), ('Femme', 'Femme')])
    numero_de_telephone = models.CharField(max_length=20, blank=False)
    email = models.EmailField()
    domaine_activite = models.CharField(max_length=100, blank=False)
    ville_ou_commune = models.CharField(max_length=100, blank=False)
    localisation_atelier = models.CharField(max_length=200, blank=False)
    photo_de_profil = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    portfolio_photos = models.ManyToManyField('PortfolioPhoto', blank=True)
    titres_diplomes = models.TextField(blank=True, help_text="Entrez les titres des diplômes séparés par des virgules")
    annees_experience = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.nom} {self.prenom}"

class PortfolioPhoto(models.Model):
    photo = models.ImageField(upload_to='portfolio_photos/', blank=True, null=True)
    

# Model d'enregistrement client :

class InscriptionClient(models.Model):
    nom = models.CharField(max_length=50, blank=False)
    prenom = models.CharField(max_length=70, blank=False)
    ville_ou_commune = models.CharField(max_length=70, blank=False)
    numero_de_telephone = models.CharField(max_length=20, blank=False)
    mot_de_passe= models.CharField(max_length=60, null=True) 
    confirmer_le_mot_de_passe= models.CharField(max_length=60, null=True) 

# Model d'enregistrement d'artisans :

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)



class User(AbstractBaseUser):
    nom = models.CharField(max_length=50, blank=False)
    prenom = models.CharField(max_length=50, blank=False)
    genre = models.CharField(max_length=10, choices=[('Homme', 'Homme'), ('Femme', 'Femme')])
    numero_de_telephone = models.CharField(max_length=20, blank=False)
    email = models.EmailField(unique=True)
    domaine_activite = models.CharField(max_length=70, blank=False)
    ville_ou_commune = models.CharField(max_length=70, blank=False)
    localisation_atelier = models.CharField(max_length=200, blank=False)
    photo_de_profil = models.ImageField(upload_to='photo_de_profil/', blank=True, null=True)
    mot_de_passe= models.CharField(max_length=60, null=True) 
    confirmer_le_mot_de_passe= models.CharField(max_length=60, null=True) 
    
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nom', 'prenom']

    def __str__(self):
        return self.email





    

ArtisanFinder/forms.py
from django import forms
from .models import InscriptionClient, Artisan
from .models import Artisan, PortfolioPhoto, User, UserManager
from django.contrib.auth.forms import UserCreationForm


# Formulaire d'inscription Artisan:
class ArtisanForm(forms.ModelForm):
    class Meta:
        model = Artisan
        fields = [
            'nom', 'prenom', 'genre', 'numero_de_telephone', 'email', 'domaine_activite', 
            'ville_ou_commune', 'localisation_atelier', 'photo_de_profil', 'titres_diplomes',
            'annees_experience'
        ]

class PortfolioPhotoForm(forms.ModelForm):
    class Meta:
        model = PortfolioPhoto
        fields = ['photo']

# Formulaire de connexion :

class LoginForm(forms.Form):
    numero_de_telephone = forms.CharField(
        label='Numéro de téléphone',
        widget=forms.TextInput(attrs={'placeholder': 'Numéro de téléphone', 'class': 'form-control'})
    )
    mot_de_passe = forms.CharField(
        label='Mot de passe',
        widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe', 'class': 'form-control'})
    )
    se_souvenir_de_moi = forms.BooleanField(
        label='Se souvenir de moi',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )
    
    

class ArtisanSignUpForm(UserCreationForm):
    mot_de_passe = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Entrez votre mot de passe'}),
        error_messages={
            'required': "Veuillez entrer un mot de passe.",
        }
    )
    confirmer_le_mot_de_passe = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirmer votre mot de passe'}),
        error_messages={
            'required': "Veuillez confirmer votre mot de passe.",
        }
    )

    class Meta:
        model = Artisan
        fields = ['nom', 'prenom', 'genre', 'numero_de_telephone', 'email', 'domaine_activite', 'ville_ou_commune', 'localisation_atelier', 'photo_de_profil']
        widgets = {
            'nom': forms.TextInput(attrs={'placeholder': 'Entrez votre nom'}),
            'prenom': forms.TextInput(attrs={'placeholder': 'Entrez votre prénom'}),
            'genre': forms.Select(attrs={'placeholder': 'Genre'}),
            'numero_de_telephone': forms.TextInput(attrs={'placeholder': 'Entrez votre numéro de téléphone'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'domaine_activite': forms.TextInput(attrs={'placeholder': 'Entrez votre domaine d\'activité'}),
            'ville_ou_commune': forms.TextInput(attrs={'placeholder': 'Entrez votre ville ou commune'}),
            'localisation_atelier': forms.TextInput(attrs={'placeholder': 'Précisez la localisation de votre atelier ou lieu de travail'}),
            'photo_de_profil': forms.ClearableFileInput(attrs={'placeholder': 'Photo de profil'}),
        }
        error_messages = {
            'nom': {
                'required': "Le nom est obligatoire.",
                'max_length': "Le nom ne peut pas dépasser 100 caractères."
            },
            'prenom': {
                'required': "Le prénom est obligatoire.",
                'max_length': "Le prénom ne peut pas dépasser 100 caractères."
            },
            'genre': {
                'required': "Le genre est obligatoire.",
            },
            'numero_de_telephone': {
                'required': "Le numéro de téléphone est obligatoire.",
                'max_length': "Le numéro de téléphone ne peut pas dépasser 20 caractères."
            },
            'email': {
                'required': "L'adresse email est obligatoire.",
                'invalid': "Veuillez entrer une adresse email valide.",
                'unique': "Un utilisateur avec cette adresse email existe déjà."
            },
            'domaine_activite': {
                'required': "Le métier est obligatoire.",
                'max_length': "Le métier ne peut pas dépasser 100 caractères."
            },
            'ville_ou_commune': {
                'required': "La ville ou commune est obligatoire.",
                'max_length': "La ville ou commune ne peut pas dépasser 100 caractères."
            },
            'localisation_atelier': {
                'required': "La localisation de l'atelier est obligatoire.",
                'max_length': "La localisation de l'atelier ne peut pas dépasser 200 caractères."
            },
            'photo_de_profil': {
                'invalid': "Veuillez télécharger une image valide."
            }
        }

    def clean(self):
        cleaned_data = super().clean()
        mot_de_passe = cleaned_data.get("mot_de_passe")
        confirmer_le_mot_de_passe = cleaned_data.get("confirmer_le_mot_de_passe")

        if mot_de_passe != confirmer_le_mot_de_passe:
            self.add_error('confirmer_le_mot_de_passe', "Les mots de passe ne correspondent pas.")
        return cleaned_data
    
    
class InscriptionClientForm(forms.ModelForm):
     mot_de_passe = forms.CharField(widget=forms.PasswordInput,required=False)
     confirmer_le_mot_de_passe = forms.CharField(widget=forms.PasswordInput,required=False)
     class Meta:
        model = InscriptionClient
        fields = ['nom', 'prenom', 'ville_ou_commune', 'numero_de_telephone','mot_de_passe','confirmer_le_mot_de_passe']
        error_messages = {
            'nom': {
                'required': "",
            },
            'prenom': {
                'required': "",
            },
            'ville_ou_commune': {
                'required': "",
            },
            'numero_de_telephone': {
                'required': "",
            },
             'mot_de_passe': {
                'required': "",
            },
             
            'confirmer_le_mot_de_passe': {
                'required': "",
            },
        }
        
     def clean(self):
        cleaned_data = super().clean()
        mot_de_passe = cleaned_data.get("mot_de_passe")
        confirmer_le_mot_de_passe = cleaned_data.get("confirmer_le_mot_de_passe")

        if mot_de_passe != confirmer_le_mot_de_passe:
            raise forms.ValidationError("Les mots de passe ne sont pas identiques")

templates/accueil.html
{% extends 'base.html' %}
{% load static  %}
{% block title %}Page d'accueil{% endblock %}

{% block content %}

    <!-- Carousel (slider)-->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'artisanfinder/images/slide2.png' %}" class="d-block w-100" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Premier Slide</h5>
                    <p>Soudeur.</p> -->
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'artisanfinder/images/slide2.png' %}" class="d-block w-100" alt="Second slide">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Deuxième Slide</h5>
                    <p>Electromécanicien.</p> -->
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'artisanfinder/images/slide3.png' %}" class="d-block w-100" alt="Third slide">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Troisième Slide</h5> -->
                    <!-- <p>Plombier.</p> -->
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'artisanfinder/images/slide4.png' %}" class="d-block w-100" alt="Third slide">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>   </h5> -->
                    <!-- <p>Mécanicien.</p> -->
                </div>
            </div>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="précédent">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">précédent</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="suivant">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">suivant</span>
        </a>
    </div>

    <!-- Contenu principal -->
    <div class="container mt-5">
        <div class="jumbotron">
            <h1 class="display-4">Bienvenue sur Artisan Finder</h1>
            <p class="lead">Nous offrons les meilleurs services pour trouver des artisans qualifiés.</p>
            <hr class="my-4">
            <h5 class="display-6">Nos domaines d'intervention : </h5>
              <!-- NOS DOMAINES D'INTERVENTION DEBUT -->
              
              <div class="row" style="row-gap:50px" data-v-fd595cb8=""><div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/icone-plomberie.png' %}" alt="icone-plomberie" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Plomberie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/icone-electricite.png' %}" alt="icone-electricite" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Electricité
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/icone-froid..png' %}" alt="icone-froid" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Climatisation
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/icone-carrelage.png' %}" alt="icone-carreleur" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Carrelage
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/ferronerie.png' %}" alt="icone-fixation-objets" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Ferronnerie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/menuiserie.png' %}" alt="icone-menuserie" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Menuiserie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/peinture.png' %}" alt="icone-ferronerie" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Peinture
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/ferronerie.png' %}" alt="icone-ferronerie" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Serrurerie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/maçon.png' %}" alt="icone-macon" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Maçonnerie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/jardinier.png' %}" alt="icone-jardinier" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Jardinerie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/icone-staffeur.png' %}" alt="icone-staffeur" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Stafferie
            </a></div> <div class="col-lg-2 col-xl-2 col-md-3 col-sm-3 mt-5" style="text-align:center" data-v-fd595cb8=""><a data-v-fd595cb8=""><img src="{% static 'artisanfinder/images/vitrier.png' %}" alt="icone-vitrier-alu" width="96" height="96" class="img-reservations" style="cursor:pointer" data-v-fd595cb8=""> <br data-v-fd595cb8="">
                Vitrerie ALU
            </a></div></div>



              <!-- DOMAINE D'INTERVENTION FIN -->
            <hr class="my-4">
            <p>Explorez nos services pour en savoir plus.</p>
            <a class="btn btn-primary btn-lg my-3" href="{% url 'services' %}" role="button">En savoir plus</a>
        </div>
    </div>

<!-- Le pieds de pages --> {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'artisanfinder/css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <link rel="stylesheet" href="static/images">

    <!-- Bootstrap JS and dependencies -->
    <script src="{% static 'artisanfinder/js/jquery.js'   %}"></script>
    <script src="{% static 'artisanfinder/js/popper.js'   %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>

    <main>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-custom">
            <a class="navbar-brand" href="/"><i class="fas fa-home"></i></a>
            <img width="60px" height="40px" src="{% static 'artisanfinder/images/logo3.png' %}" alt="logo">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/"><i class="fas fa-home"></i> Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/services/"><i class="fas fa-concierge-bell"></i> Nos services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/artisan/"><i class="fas fa-search"></i> Trouver un artisan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/espaceArtisan/"><i class="fas fa-briefcase"></i> Espace artisan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/connexion/"><i class="fas fa-sign-in-alt"></i> Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact/"><i class="fas fa-envelope"></i> Nous contacter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/apropos/"><i class="fas fa-info-circle"></i> À propos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-user"></i></a>

                    </li>
                </ul>
                
            </div>
        </nav>

        <!-- Sidebar with Social Icons -->
        <div class="sidebar">
            <a href="https://web.facebook.com/artisan.finder.2024?mibextid=kFxxJD&_rdc=1&_rdr" target="_blank"><i
                    class="fab fa-facebook-f"></i></a>
            <a href="https://www.instagram.com/arti.sanfinder495" target="_blank"><i class="fab fa-instagram"></i></a>
            <a href="https://www.linkedin.com" target="_blank"><i class="fab fa-linkedin-in"></i></a>
            <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="https://www.youtube.com/@FinderArtisan" target="_blank"><i class="fab fa-youtube"></i></a>
            <a href="https://www.whatsapp.com" target="_blank"><i class="fab fa-whatsapp"></i></a>
            <a href="http://tiktok.com/@artisan.finder" target="_blank"><i class="fab fa-tiktok"></i></a>
        </div>

        <!-- Main Content -->
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <!-- Footer -->
    <footer class="footer p-5">
        <div class="footer_row bg-success">
            <ul class="col-12 text-center my-3">
                <li class="d-inline-block m-3">
                    <a href="/mentions-legales" title="Vers la page les mentions légales de l'entreprise 22"
                        rel="nofollow" class="text-decoration-none text-white">Mentions légales</a>
                </li>
                <li class="d-inline-block m-3">
                    <a href="/vieprivee" title="Vers la page vie privée du site Artisan Finder" rel="nofollow"
                        class="text-decoration-none text-white">Vie privée</a>
                </li>
                <li class="d-inline-block m-3">
                    <a href="/cgu" title="Vers la page des conditions générales d'utilisation du Artisan Finder"
                        rel="nofollow" class="text-decoration-none text-white">CGU</a>
                </li>
                <li class="d-inline-block m-3">
                    <a href="/cgv" title="Vers la page des conditions générales de vente du site Artisan Finder"
                        rel="nofollow" class="text-decoration-none text-white">CGV</a>
                </li>
                <li class="d-inline-block m-3">
                    <a href="/equipe" title="Vers la page de l'équipe" rel="nofollow"
                        class="text-decoration-none text-white">Equipe</a>
                </li>
                <li class="d-inline-block m-3">
                    <a href="/contact" title="Vers la page de contact" rel="nofollow"
                        class="text-decoration-none text-white">Contact</a>
                </li>
            </ul>
            <p class="text-white text-center">© Entreprise 22 2024</p>
        </div>
    </footer>
</body>

</html>

templates/edit_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cgv{% endblock %}

{% block content %}

<main>
<h5 class="display-6 text-center my-3">Modification du mot de passe : </h5>


<h1>Changer le mot de passe</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Changer le mot de passe</button>
</form>


</main>
<!-- Le pieds de pages -->{% endblock %}

templates/espace_artisan.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Espace artisan{% endblock %}

{% block content %}

<main>
<h5 class="display-6 text-center my-3">Espace artisan : </h5>
 
<h6></h6>





</main>
<!-- Le pieds de pages -->{% endblock %}

templates/inscription_client.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inscription client{% endblock %}

{% block content %}


<main>

    
   
    <div class="container mt-5">
        
        <div class="contact-form">
            <h2 class="bg-success text-white text-center">Inscription client  </h2>
            <form method="post" action="{% url 'client-inscription' %}">
                {% csrf_token %}
                <div>
                    <label for="id_nom">Nom:</label>
                    {{ form.nom }}
                    <!-- Personnalisation des erreurs -->
                    {% for error in form.nom.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            
                <div>
                    <label for="id_prenom">Prénom:</label>
                    {{ form.prenom }}
                    {% for error in form.prenom.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            
                <div>
                    <label for="id_ville_ou_commune">Ville ou Commune:</label>
                    {{ form.ville_ou_commune }}
                    {% for error in form.ville_ou_commune.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            
                <div>
                    <label for="id_numero_de_telephone">Numéro de téléphone:</label>
                    {{ form.numero_de_telephone }}
                    {% for error in form.numero_de_telephone.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>

                <div>
                    <label for="id_mot_de_passe">Mot de passe :</label>
                    {{ form.mot_de_passe }}
                    {% for error in form.mot_de_passe.errors %}
                    <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>

                <div>
                    <label for="id_confirmer_le_mot_de_passe">Confirmer le mot de passe :</label>
                    {{ form.confirmer_le_mot_de_passe }}
                    {% for error in form.confirmer_le_mot_de_passe.errors %}
                    <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            
                <button class="btn btn-success" type="submit">S'inscrire</button>
            </form>
        </div>
    </div>



</main>








<!-- Le pieds de pages -->{% endblock %}

templates/mentions.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Connexion{% endblock %}

{% block content %}

<main>
<h5 class="display-6 text-center my-3">Mentions légales : </h5>





</main>
<!-- Le pieds de pages -->{% endblock %}